In [2]:
import numpy as np
import random

#### Matrix Addition

In [54]:
# Use numpy to generate matrix array for x, y & c
x = np.random.randint(low = 0, high = 9, size=(3,3),dtype='int')
print(x)

y = np.random.randint(low = 0, high = 9, size=(3,3),dtype='int')
print(y)

c = np.zeros((3,3),dtype='int')
print(c)

# Loops through each element in the 3 list that make up x
# Loops through each element in the 3 list that make up y
# adds the x & y elements that are at the same position
for i in range(len(x)):
    for j in range(len(x[0])):

        c[i][j] = (x[i][j]+y[i][j])
print(c)

[[2 3 6]
 [1 2 6]
 [8 4 2]]


In [80]:
rows_A, col_A = a.shape
rows_B, col_B = b.shape


3
4
4
3


#### Matrix multiplication

In [102]:
# Use numpy to generate matrix array for x, y & c
a = np.random.randint(low = 0, high = 9, size=(2,2),dtype='int')
print(a,'\n')

b = np.random.randint(low = 0, high = 9, size=(2,2),dtype='int')
print(b,'\n')

z = np.zeros((2,2),dtype='int')

# Get the dimensions of a & b
rows_A, cols_A = a.shape
rows_B, cols_B = b.shape

# Check to see if matrix multiplication is possible
# Only when the number of columns in a = number of rows in b
if cols_A != rows_B:
    raise ValueError("Number of columns in 'a' must match the number of rows in 'b'")

for i in range(rows_A):
    for j in range(cols_B):
        for k in range(cols_A):
            z[i][j] += a[i][k]*b[k][j]
print(z)


[[0 6]
 [0 7]] 

[[1 5]
 [6 2]] 

[[36 12]
 [42 14]]


### Lets make a matrix calculator

In [2]:
import streamlit as st
import numpy as np

In [3]:
st.title('Matrix calculator')
st.subheader('Enter dimensions and desired task (addition/subtraction or multiplication)')

2025-04-05 17:06:37.757 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-05 17:06:37.824 
  command:

    streamlit run /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ipykernel_launcher.py [ARGUMENTS]
2025-04-05 17:06:37.824 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-05 17:06:37.825 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-05 17:06:37.825 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.


DeltaGenerator()